Enable test_det_logdet_slogdet on ROCm
ROCm/pytorch pull request #1138
Opened 2022-11-07 18:46 UTC by BLOrange-AMD

2022-11-07 19:07 UTC, pruthvistony requested changes

2022-11-07 19:07 UTC, pruthvistony commented on test/test_linalg.py
> -    @skipCUDAIfNoCusolver
This decorator should be `@skipCUDAIfNoHipsolverOrCusolver`

2022-11-09 22:26 UTC, pruthvistony commented
jenkins please retest

2022-11-09 23:22 UTC, pruthvistony commented
jenkins retest this please

2022-11-13 16:44 UTC, BLOrange-AMD commented
jenkins retest this please

2022-11-14 19:16 UTC, pruthvistony commented
jenkins retest this please

2023-01-18 15:31 UTC, BLOrange-AMD commented
jenkins retest this please

2024-08-28 05:54 UTC, closed without merging