Update build_triton_wheel.py to update base repo name for triton
ROCm/pytorch pull request #1637
Opened 2024-10-17 15:40 UTC by ethanwee1

Fixes http://rocm-ci.amd.com/job/pytorch-pipeline-manylinux-wheel-builder_rel-6.2/
and https://ontrack-internal.amd.com/browse/SWDEV-483979

2024-10-17 15:50 UTC, rocm-mici commented
Jenkins build for [1ba5642f0a50fb59108341941eb240008dcff53b](https://github.com/ROCm/pytorch/commit/1ba5642f0a50fb59108341941eb240008dcff53b) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1637/1//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1637/1/artifact)

2024-10-17 18:39 UTC, jithunnair-amd approved these changes
LGTM. Need to test

2024-10-17 20:53 UTC, rocm-mici commented
Jenkins build for [5126f20b3b44250b4f4bef3677b34de2f8c61ebb](https://github.com/ROCm/pytorch/commit/5126f20b3b44250b4f4bef3677b34de2f8c61ebb) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1637/2//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1637/2/artifact)

2024-10-18 05:33 UTC, pruthvistony requested changes

2024-10-18 05:33 UTC, pruthvistony commented on .github/scripts/build_triton_wheel.py
> +            triton_repo = "https://github.com/ROCmSoftwarePlatform/triton"
Change to - "https://github.com/ROCm/triton"

2024-10-18 16:56 UTC, rocm-mici commented
Jenkins build for [0b236e47a9777ea2508f7f961cd49ba655ef211c](https://github.com/ROCm/pytorch/commit/0b236e47a9777ea2508f7f961cd49ba655ef211c) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1637/3//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1637/3/artifact)

2024-10-19 12:57 UTC, rocm-mici commented
Jenkins build for [0b236e47a9777ea2508f7f961cd49ba655ef211c](https://github.com/ROCm/pytorch/commit/0b236e47a9777ea2508f7f961cd49ba655ef211c) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1637/4//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1637/4/artifact)

2025-02-13 22:14 UTC, closed without merging